CarManager/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarManager.DAL.Repositories;
using CarManager.Models;


namespace CarManager.Controllers
{
    public class CarController : Controller
    {
        private CarUnitOfWork repository = new CarUnitOfWork();

        // GET: Car
        public ActionResult Index()
        {
            return View( repository.Cars.GetAll() );
        }

        [HttpGet]
        [Authorize( Roles = "admin" )]
        public ActionResult AddCar()
        {
            return View( "AddCar" );
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult AddCar( Car car )
        {
            car.IsFree = true;
            repository.Cars.Create( car );
            return View( "Index", repository.Cars.GetAll() );
        }


        [HttpGet]
        [Authorize( Roles = "admin" )]
        public ActionResult EditCar( int? id )
        {
            if (id == null)
                return HttpNotFound();

            Car car = repository.Cars.Get( (int)id );

            if ( car != null )
                return View( "EditCar", car );

            return HttpNotFound();
        }


        [HttpPost]
        [Authorize( Roles = "admin" )]
        public ActionResult EditCar( Car car )
        {
            repository.Cars.Update( car );
            return View( "Index", repository.Routes.GetAll() );
        }
        
    }
}

CarManager/Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarManager.DAL.Repositories;
using CarManager.Models;

namespace CarManager.Controllers
{
    public class DriverController : Controller
    {
        private CarUnitOfWork repository = new CarUnitOfWork();

        // GET: Driver
        public ActionResult Index()
        {
            return View( repository.Drivers.GetAll() );
        }

        public ActionResult DriverDetails( int? id )
        {
            if ( id == null )
                return HttpNotFound();

            Driver driver = repository.Drivers.Get( (int)id );

            if ( driver == null )
                return HttpNotFound();
            
            return View( "DriverDetails", driver );
        }


        //public ActionResult AddDriver()
        //{

        //}
    }
}

CarManager/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using CarManager.DAL.Repositories;
using CarManager.Models;


namespace CarManager.Controllers
{
    public class RequestController : Controller
    {
        private CarUnitOfWork repository = new CarUnitOfWork();
        

        public ActionResult Index()
        {
            return View( repository.Requests.GetAll() );
        }


        [HttpGet]
        [Authorize( Roles = "admin, driver")]
        public ActionResult AddRequest()
        {
            return View( "AddRequest" );
        }


        [HttpPost]
        [Authorize(Roles = "admin, driver")]
        public ActionResult AddRequest( Request request )
        {
            //if( !repository.Drivers.GetAll().Any( d => d.LicenseNumber == request.DriverLicenseNumber ) )
            //{
            //    ModelState.AddModelError( "", "This license number is not exist!" );
            //    return View( "AddRequest" );
            //}

            repository.Requests.Create( request );
            return View( "Index", repository.Requests.GetAll() );

        }


        public ActionResult ChooseCar( int? requestId )
        {

            if ( requestId == null )
                return HttpNotFound();

            Request request = repository.Requests.Get( (int)requestId );

            IEnumerable<Car> selectedCars 
                = repository.Cars.Find( c => c.IsFree == true 
                                        && c.IsBroken == false 
                                        && c.CarryingCapacity >= request.CarryingCapacity );

            ViewBag.requestId = requestId;

            return View( "CarList", selectedCars );
        }


        public ActionResult SelectCar( int? requestId, int? carId )
        {
            if ( requestId == null || carId == null)
                return HttpNotFound();

            Request request = repository.Requests.Get( (int) requestId );
            Car car = repository.Cars.Get( (int)carId );


            car.IsFree = false;
            request.Car = car;

            repository.Requests.Update( request );
            repository.Cars.Update( car );


            return View( "AddRequest" );  //MAIN PAGE
        }
    }
}

CarManager/Controllers/RouteController.cs
using System;
using System.Web.Mvc;
using System.Linq;
using CarManager.DAL.Repositories;
using CarManager.Models;


namespace CarManager.Controllers
{
    public class RouteController : Controller
    {
        private CarUnitOfWork repository = new CarUnitOfWork();


        [Authorize(Roles = "admin, operator")]
        public ActionResult Index()
        {
            return View( repository.Routes.GetAll() );
        }


        [HttpGet]
        [Authorize(Roles = "admin, operator")]
        public ActionResult EditRoute( int? id )
        {
            if ( id == null )
                return HttpNotFound();

            DeliveryRoute editRoute = repository.Routes.Get( (int)id );

            if ( editRoute != null )
                return View( "EditRoute", editRoute );

            return HttpNotFound();
        }


        [HttpPost]
        [Authorize( Roles = "admin, operator" )]
        public ActionResult EditRoute( DeliveryRoute route )
        {
            repository.Routes.Update( route );
            return View( "Index", repository.Routes.GetAll() );
        }


        [HttpGet]
        [Authorize( Roles = "admin, operator" )]
        public ActionResult AddDeliveryRoute()
        {
            return View( "AddDeliveryRoute" ); 
        }


        [HttpPost]
        [Authorize( Roles = "admin, operator" )]
        public ActionResult AddDeliveryRoute( DeliveryRoute route )
        {
            repository.Routes.Create( route );
            return View( "Index", repository.Routes.GetAll() );

        }

        
        public ActionResult SortRoutesById() ///CHANGE HERE AND ALL BRUNCH
        {
            return PartialView( "DeliveryRoutesList", repository.Routes.GetAll().OrderBy( r => r.Id ));
        }


        public ActionResult SortRoutesByCreatedTime()
        {
            return PartialView( "DeliveryRoutesList", repository.Routes.GetAll().OrderBy( r => r.Created ));
        }

        public ActionResult SortRoutesByStatus()
        {
            return PartialView( "DeliveryRoutesList", repository.Routes.GetAll().OrderBy( r => r.Status ));
        }
        
    }
}

CarManager/Views/Layout/CarManagerLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />

</head>
<body>
    <div class="wrapper">
        <div class="page-header" id="back-to-top">
            <p>@ViewBag.Title</p>
            <div class="login-menu">
                @if ( !String.IsNullOrEmpty( User.Identity.Name ) )
                {
                    <p> You logged like @User.Identity.Name </p>
                    @Html.ActionLink( "Log Out", "Logout", "Account" )
                }
                else
                {
                    <p> "You need to login" </p>
                    @Html.ActionLink("Registration", "Register", "Account")
                    @Html.ActionLink( "Log In", "Login", "Account" )
                }
            </div>
        </div>
        <div class="widget">
            <ul class="widget-list">
                <li> @Html.ActionLink( "Route List", "Index", "Route" )</li>
                <li> @Html.ActionLink( "Driver List", "Index", "Driver" ) </li>
                <li> @Html.ActionLink( "Add New Request", "AddRequest", "Request" ) </li>
                <li> @Html.ActionLink( "Add New User", "Register", "Account" ) </li>
                <li> @Html.ActionLink( "Cars", "Index", "Car" ) </li>


            </ul>

        </div>
        <div class="body-content">
            @RenderBody()
        </div>
        <footer>
            <hr />
            <p> Copyright &copy; @DateTime.Now.Year - Car Manager. All rights reserved.</p>
            <a href="#back-to-top">Back to top</a>
        </footer>
    </div>
    
    @RenderSection("Scripts", false)
</body>
</html>